# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: かほさん的树洞
subtitle: ''
description: ''
keywords:
author: kaho
language: zh-cn
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://blog.kahosan.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
about_dir: about
util_dir: util
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# 代码高亮
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: typography
plugin:
  - hexo-generator-category-enhance
  - hexo-generator-feed
  - hexo-toc
  - hexo-generator-robotstxt
  # ... other plugins you'd like to enable

# Generate archive page
archive_generator:
  per_page: 0

# Generate categories index page and each category page
category_generator:
  per_page: 10
  enable_index_page: true

# Generate tags index page and each tag page
tag_generator:
  per_page: 10
  enable_index_page: true

# Generator atom feed for you website
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

  
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# deploy:
#   type: git
#   repo: git@23.225.91.186:/home/git/repo/blog.git
#   # example, https://github.com/hexojs/hexojs.github.io
#   branch: master

# deploy:
#   type: git
#   repo: https://github.com/kahosan/kahosan.github.io.git
#   branch: master
  



# Generate search index file
# search:
#   path: search.xml
#   field: post
#   content: true

# Minifier
# all_minifier: true
# image_minifier:
#   enable: false
#   interlaced: false
#   multipass: false
#   optimizationLevel: 2
#   pngquant: false
#   progressive: false
#   silent: false

## Hexo-minify Default Config Options
minify:
  js:
    enable: true
    ## 详细配置: https://github.com/mishoo/UglifyJS
    options:
  css:
    enable: true
    ## 详细配置: https://github.com/clean-css/clean-css#compatibility-modes
    options:
  html:
    enable: true
    ## 详细配置: https://github.com/kangax/html-minifier#options-quick-reference
    options: 
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  # + 1.2.0 版本新增
  postcss:
    enable: false
    ## 详细配置: https://github.com/postcss/autoprefixer#options
    ## 注意Hexo-minify仅内置了autoprefixer插件
    ## 受Hexo限制，目前无法实现自定义postcss插件
    options: 
      # JavaScript 数组写法
      # overrideBrowserslist: ['> 1%', 'last 2 versions', 'not dead']
      # YAML 数组写法
      overrideBrowserslist: 
        - '> 1%' # 特殊符号需要使用'或"
        - last 2 versions
        - not dead

# Lazyload
# lazyload:
#   enable: false
#   onlypost: false # optional
#   loadingImg: https://npm.elemecdn.com/skx@0.0.9/img/lazy.gif #/images/loading.gif
#   isSPA: false # optional
#   preloadRatio: 3 # optional, default is 1

#sitemap
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap_template.xml
  template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true

#robots
robotstxt:
  useragent: "*"
  disallow:
    - /ping
    - /beacon
    - /js/jquery.js
    - /data
    - /disqus
    - '*.md'
  allow:
    - /
  sitemap: https://blog.kahosan.top/sitemap.xml