# fix for vercel
packages:
  - "."

allowBuilds:
  cwebp-bin: false
  hexo-util: false
  jpegtran-bin: false
  pngquant-bin: false
  ttf2woff2: false

  # fix ci
  sharp: false
  esbuild: false
  workerd: false
