name = "kaho_blog"
type = "webpack"
usage_model = ''
compatibility_flags = []
workers_dev = false
account_id = "$CF_ACCOUNT_ID"
route = "blog.kahosan.top/*"
zone_id = "$CF_ZONE_ID"
site = {bucket = "./public", entry-point = "workers-site"}