name = "kaho_blog"
workers_dev = false
account_id = "689fc74db37d94d7bf42a5bbf4931407"
route = "blog.kahosan.top/*"
compatibility_date = "2022-03-20"
main = "workers-site/index.js"

[site]
bucket = "./public"